---

language: python
python: "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get --reinstall install -qq python-apt python2.7
  - sudo apt-get --reinstall install -qq apt-transport-https ca-certificates curl software-properties-common
  - sudo apt-get remove docker-ce

install:
  - pip install ansible pyasn1 urllib3 pyOpenSSL ndg-httpsclient
  - which ansible-playbook

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become
  - docker version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
