---

language: python
python: "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt
  - sudo apt-get --reinstall install -qq apt-transport-https ca-certificates curl software-properties-common
  - sudo apt-get remove docker-ce

install:
  - pip3 install ansible
  - which ansible-playbook
  - ls -lha ~/.local/bin/

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become
  - docker version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
